name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build and Test
        run: |
          ./gradlew build
          ./gradlew test

      - name: Check Code Style
        run: |
          ./gradlew checkstyleMain

      - name: Build Docker Image
        run: |
         echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

      - name: Push to Docker Registry
        run: |
          docker tag mem-creator:latest ppuchinski/mem-creator:latest
          docker push ppuchinski/mem-creator:latest
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}



